### ISSUE TITLE
Define what license applies to which files

### ISSUE THREAD

**Issue by dvzrv** [osxmidi/LinVst3#10]
Hi!

For packaging and general re-usability purposes it would be great if you could define specifically what license applies to which files.
The general GPL3-or-later license seems to cover the code, but there are also bits by Steinberg that seem to be covered by a BSD-3-clause or similar.
These specifics are usually explained in a COPYING file or in the README itself.

To allow people to package this software - I for one am considering it for Arch Linux :) - please also add separate license files for the respective files (extracting the license text from the README.md is rather cumbersome).

Thanks a lot! :)

**Comment by osxmidi** [comment]
> Hi!
> 
> For packaging and general re-usability purposes it would be great if you could define specifically what license applies to which files.
> The general GPL3-or-later license seems to cover the code, but there are also bits by Steinberg that seem to be covered by a BSD-3-clause or similar.
> These specifics are usually explained in a COPYING file or in the README itself.
> 
> To allow people to package this software - I for one am considering it for Arch Linux :) - please also add separate license files for the respective files (extracting the license text from the README.md is rather cumbersome).
> 
> Thanks a lot! :)

I'll make a more detailed license outline.

Basically, the 

basewrapper.cpp

basewrapper.h

basewrapper.sdk.cpp

docvst2.h

vst2wrapper.cpp

vst2wrapper.h

vst2wrapper.sdk.cpp

files are Steinberg's and have the below license

The other files are LinVst files with a GPL-3 license.

A binary also uses the files in the Steinberg Vst3 SDK.

//-----------------------------------------------------------------------------
// LICENSE
// (c) 2018, Steinberg Media Technologies GmbH, All Rights Reserved
//-----------------------------------------------------------------------------
// Redistribution and use in source and binary forms, with or without modification,
// are permitted provided that the following conditions are met:
// 
//   * Redistributions of source code must retain the above copyright notice, 
//     this list of conditions and the following disclaimer.
//   * Redistributions in binary form must reproduce the above copyright notice,
//     this list of conditions and the following disclaimer in the documentation 
//     and/or other materials provided with the distribution.
//   * Neither the name of the Steinberg Media Technologies nor the names of its
//     contributors may be used to endorse or promote products derived from this 
//     software without specific prior written permission.
// 
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
// IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, 
// INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, 
// BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, 
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF 
// LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE 
// OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE  OF THIS SOFTWARE, EVEN IF ADVISED
// OF THE POSSIBILITY OF SUCH DAMAGE.
//-----------------------------------------------------------------------------
